package util;

import sun.misc.BASE64Decoder;

public class Test {

	public static void main(String[] args) throws Exception {
		String result = "eyJpdGVtTGlzdCI6W3siZ29vZHNJZCI6IjNGNTgwMCAzMEM3IEYwMDExIiwidGl0bGUiOiJQcmFkYcbVwK207yDGvbXX0KwgxaPGpCDXz7rsyas70dXJqzogs9+05zozNi41ILnmuPE6zrS5/fXXfMWjxqTWxtCsw+Z8z/C9utbG0Ky113zQodPaMjRDTXxQcmFkYcXGfDFGNzEwRSDGt8XGOlByYWRhxtXArbTvIiwibnVtIjoiMCIsImRlc2MiOiLR1cmrOiCz37TnOjM2LjUguea48TrOtLn99dd8xaPGpNbG0KzD5nzP8L261sbQrLXXfNCh09oyNENNfFByYWRhxcZ8MUY3MTBFIMa3xcY6UHJhZGHG1cCttO8iLCJwcmljZSI6IjAiLCJwb3N0RmVlIjoiMCIsImV4cGVzc0ZlZSI6IjAiLCJlbXNGZWUiOiIwIiwib3V0ZXJJZCI6IiIsImxpc3RUaW1lIjoiMjAxNC0wOS0xNiAxMDowMzoyNiIsInR5cGUiOiJmaXhlZCIsImFwcHJvdmVTdGF0dXMiOiJvbnNhbGUiLCJza3VMaXN0IjpbeyJza3VJZCI6IjI5NDQzMTU5Iiwic2t1SGdJZCI6IjI5NDQzMTU5IiwiaXNicyI6InRydWUiLCJoZ3pjIjoiSDgwMTJXMDAwMDA1IiwiaGd4aCI6IjQwIiwib3duZXJDb2RlIjoiNTAwNTI2MDJCRSIsIm93bmVyTmFtZSI6ItbYx+zJzMnntefX08nMzvHT0M/euavLviIsInNrdVNwZWNJZCI6IiIsIm91dGVySWQiOiIiLCJiYXJjb2RlIjoiMjk0NDMxNTkiLCJudW1saWQiOiIwIiwicXVhbmxpdHkiOiIwIiwicHJpY2UiOiIwIiwic3RhdHVzIjoibm9ybWFsIiwidHlwZSI6Isirwb+4/NDCIn1dfV19";
		result = new String(new BASE64Decoder().decodeBuffer(result.replaceAll(" ", "+")),"GB2312");
		System.out.println(result);
	}

}
